export default [
  {
    name: 'Registration',
    duration: 30,
  },
  // Hall 1
  [
    {
      name: 'Opening',
      duration: 30,
    },
    {
      name: 'Micro Frontend Architecture: A new way of building scalable web applications',
      speakerId: 'lilit',
      duration: 35,
      levels: [1, 2],
      lang: 'am',
      videoUrl: 'https://bit.ly/3twoshv',
    },
    {
      name: 'Babylon.js: Black Jack',
      speakerId: 'varuzhan',
      duration: 35,
      levels: [],
      lang: 'am',
    },
    {
      name: 'Psychology of Rerenders',
      speakerId: 'hrach',
      duration: 35,
      levels: [],
      lang: 'am',
      videoUrl: 'https://bit.ly/353njoj',
    },
    {
      name: 'Building component library from scratch',
      speakerId: 'sandro',
      duration: 35,
      levels: [1, 2],
      lang: 'en',
      videoUrl: 'https://bit.ly/3D0CTxo',
    },
    {
      name: 'Break',
      duration: 70,
    },
    {
      name: 'Parallel universes | Node.js',
      speakerId: 'nairi',
      duration: 35,
      levels: [],
      lang: 'am',
      videoUrl: 'https://bit.ly/3JAjupv',
    },
    {
      name: 'Optimization design patterns - from games to web',
      speakerId: 'yonatan',
      duration: 35,
      levels: [],
      lang: 'en',
    },
    {
      name: 'Deno vs Node.js',
      speakerIds: ['armen', 'mike'],
      duration: 30,
      levels: [1],
      lang: 'am',
      videoUrl: 'https://bit.ly/3qOsgZV',
    },
    {
      name: 'Break',
      duration: 20,
    },
    {
      name: 'How to achieve performing rendering in the browser',
      speakerId: 'gleb',
      duration: 35,
      levels: [],
      lang: 'ru',
      videoUrl: 'https://bit.ly/3qOsgZV',
    },
    {
      name: 'WebAssembly and how web apps are being revolutionized',
      speakerId: 'khachatur',
      duration: 35,
      levels: [1],
      lang: 'am',
      videoUrl: 'https://bit.ly/3IxKZyw',
    },
    {
      name: 'The Secrets of Successful Refactoring',
      speakerId: 'illya',
      duration: 35,
      levels: [1],
      lang: 'ru',
      videoUrl: 'https://bit.ly/36l4Kwf',
    },
    {
      name: 'Closing',
      duration: 40,
    },
  ],
  // BlackBox
  [
    {
      name: '',
      duration: 30,
    },
    {
      name: 'JavaScript and Game Development',
      speakerId: 'arsen',
      duration: 35,
      levels: [],
      lang: 'am',
      videoUrl: 'https://bit.ly/3uijVhJ',
    },
    {
      name: 'Nuxt 3. What\'s new?',
      speakerId: 'vasiliy',
      duration: 35,
      levels: [1, 2],
      lang: 'ru',
      videoUrl: 'https://bit.ly/3tvTdDe',
    },
    {
      name: 'Audio and video manipulation',
      speakerId: 'david',
      duration: 35,
      levels: [],
      lang: 'am',
      videoUrl: 'https://bit.ly/36eH9xx',
    },
    {
      name: 'Control a drone with JavaScript',
      speakerId: 'suren',
      duration: 35,
      levels: [0, 1],
      lang: 'am',
      videoUrl: 'https://bit.ly/3N9Ut6T',
    },
    {
      name: 'Break',
      duration: 70,
    },
    {
      name: 'Why you should definitely use NgRx',
      speakerId: 'armenv',
      duration: 35,
      levels: [1, 2],
      lang: 'en',
      videoUrl: 'https://bit.ly/3ty16b6',
    },
    {
      name: 'The World Beyond console.log',
      speakerId: 'davit',
      duration: 35,
      levels: [],
      lang: 'am',
      videoUrl: 'https://bit.ly/3uheUGl',
    },
    {
      name: 'Local State and Server Cache: Finding a Balance',
      speakerId: 'natalia',
      duration: 30,
      levels: [1],
      lang: 'en',
      videoUrl: 'https://bit.ly/3qqjqkw',
    },
    {
      name: 'Break',
      duration: 20,
    },
    {
      name: 'Event Store - Cool replacement for React Context',
      speakerId: 'elmira',
      duration: 35,
      levels: [1, 2],
      lang: 'am',
      videoUrl: 'https://bit.ly/3ty16b6',
    },
    {
      name: 'Micro-frontend has entered the game',
      speakerId: 'vitaly',
      duration: 35,
      levels: [1],
      lang: 'ru',
      videoUrl: 'https://bit.ly/3JA4Gay',
    },
  ],
];
